---
title: "UM *A. cervicornis* CBASS run"
subtitle: "R/V *Coral Reef II*, October 14th, 2020"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(janitor)
library(lubridate)
library(scales)
library(readxl)
library(ggthemes)
library(tidyverse)
```

# CBASS temperature logs

#### Import temperature logs for Arduino-controlled tanks
```{r}
readlog <- function(logfile, prefix) {
  read_csv(logfile) %>%
    # Remove internal header rows
    filter(PrintDate != "PrintDate") %>%
    # Format date and time
    mutate(date = as_date(Date, format = "%Y_%B_%d")) %>%
    unite(time, Th, Tm, Ts, sep = ":") %>%
    unite(dttm, date, time) %>%
    mutate(dttm = ymd_hms(dttm), hm = format(dttm, "%H:%M")) %>%
    select(dttm, hm, T1SP, TempT1, T2SP, TempT2, T3SP, TempT3, T4SP, TempT4) %>%
    # Pivot to long format
    pivot_longer(starts_with("T"), names_to = "key", values_to = "temp") %>%
    # Remove rows where temp sensors gave error codes
    filter(temp > 0, temp < 50) %>%
    # Link arduino box and sensor positions (e.g., B1T2)
    mutate(tank = str_extract(key, "T[0-9]"),
           tank = paste0(prefix, tank),
           key = case_when(grepl("SP", key) ~ str_sub(key, 3, 4),
                           TRUE ~ str_sub(key, 1, 4)),
           key = tolower(key)) %>%
    # Drop rows that did not parse a date/time
    drop_na(dttm, temp) %>%
    # Create columns for set point and actual temperature
    pivot_wider(names_from = key, values_from = temp) %>%
    # Tidy column types
    mutate(tank = factor(tank), sp = as.numeric(sp), temp = as.numeric(temp)) %>%
    # Add maximum setpoint temperature as max_temp column
    group_by(tank) %>%
    mutate(max_temp = max(sp, na.rm = TRUE)) %>%
    ungroup()
}

# Read in arduino log files
b1log <- readlog("data/20201014_UM_Acer/temperature/sdlog/20201014_BOX1_LOG.TXT", prefix = "B1")
b3log <- readlog("data/20201014_UM_Acer/temperature/sdlog/20201014_BOX3_LOG.TXT", prefix = "B3")

# Tidy arduino log files for this run
arduinolog <- bind_rows(b1log, b3log) %>%
  # Filter to just the date of this run
  filter(date(dttm) == "2020-10-14") %>%
  # Specify which arduino boxes controlled port vs. starboard tank sets
  mutate(tank_set = if_else(str_detect(tank, "B1"), "starboard", "port")) %>%
  # Add tank_id column from tank design
  left_join(read_csv("data/tank_setup.csv")) %>%
  select(dttm, hm, sp, temp, max_temp, tank_set, tank_id)
```

#### Import HOBO temperature logs for Inkbird-controlled tanks
```{r}
# Read in HOBO temperature logs
hobologfiles <- list.files("data/20201014_UM_Acer/temperature/hobo", pattern = ".xlsx", full.names = TRUE)
hobolog <- tibble(filename = hobologfiles) %>%
  mutate(log = map(filename, read_xlsx, skip = 1)) %>%
  unnest()

# Tidy HOBO temperature logs
hobolog <- hobolog %>%
  clean_names() %>%
  # Get tank_id from filename
  mutate(tank_id = str_sub(basename(filename), 1, 2)) %>%
  # Convert temps from F to C
  mutate(temp = (temp_f - 32) * 5/9) %>%
  # Select columns to keep
  select(dttm = date_time_gmt_0400, temp, tank_id) %>%
  mutate(hm = format(dttm, "%H:%M")) %>%
  # Join with tank_id information
  left_join(read_csv("data/tank_setup.csv")) %>%
  # Filter only target date
  filter(date(dttm) == "2020-10-14")

# Import inkbird setpoints
inkbird_sp <- read_csv("data/inkbird_settings.csv") %>%
  pivot_longer(2:5, names_to = "max_temp", values_to = "sp") %>%
  mutate(max_temp = as.numeric(str_extract(max_temp, "[0-9]+")),
         dttm = ymd_hms(paste("2020-10-14", time)), hm = format(dttm, "%H:%M"),
         temp = NA) %>%
  left_join(read_csv("data/tank_setup.csv")) %>%
  select(dttm, hm, sp, temp, max_temp, tank_set, tank_id)

hobolog <- bind_rows(inkbird_sp, hobolog)
```

### Plot CBASS temperature profiles and set points
```{r, fig.width = 10}
# Combine arduino and hobo temperature log data
templog <- bind_rows(arduinolog, hobolog)

# Plot
ggplot(templog, mapping = aes(x = dttm, y = temp, group = tank_id)) +
  geom_line(aes(color = tank_id), lwd = 0.2) +
  geom_step(aes(y = sp, color = tank_id), lwd = 0.5) +
  facet_wrap(~ tank_set, scales = "free") +
  scale_y_continuous(breaks = 30:38, limits = c(29, 39)) +
  scale_x_datetime(breaks = "hours", labels = label_date("%H:%M"),
                   limits = as.POSIXct(c("2020-10-14 12:00:00", "2020-10-14 21:00:00"), tz = "UTC")) +
  theme_hc() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Time of day", y = "Temperature (°C)")

write_csv(templog, "data/20201014_UM_Acer/temperature/UM_tempdata.csv")
```

# Results: PAM data

#### Import data from DIVING PAM II
```{r}
# Read manually entered data from Diving PAM II
path <- "data/20201014_UM_Acer/PAM/20201014dii_Acer.xlsx"
dpii <- path %>%
  excel_sheets() %>%
  set_names() %>%
  discard(.p = ~str_detect(.x, "Acer")) %>%
  map_df(~ read_excel(path = path, sheet = .x, range = "A1:H43", col_types = "text"), .id = "tank_id") %>%
  mutate(f = as.numeric(`F`), fm = as.numeric(`Fm'`), fvfm = as.numeric(`Y (II)`)) %>%
  select(tank_id, Geno, f, fm, fvfm) %>%
  clean_names() %>%
  mutate(geno = str_replace(geno, "-", ""),
         geno = str_replace(geno, " ", "")) %>%
  drop_na(geno)

# Combine with tank_id metadata
tanks <- read_csv("data/tank_setup.csv")
dpii <- full_join(dpii, tanks) %>%
  select(geno, f, fm, fvfm, tank_id, tank_set, max_temp)

# Fix error in data -- genotype "8yy" should be "88y"
dpii$geno[dpii$geno == "8yy"] <- "88y"

# Write collated data to file
write_csv(dpii, "data/20201014_UM_Acer/PAM/UM_pamdata.csv")
```

#### Plot raw PAM data

Color indicates possible outliers

```{r, fig.height = 10, fig.width = 10}
dpii %>%
  # If fvfm is NA, replace with zero
  replace_na(replace = list(fvfm = 0)) %>%
  ggplot(aes(x = max_temp, y = fvfm)) +
  geom_point(aes(color = max_temp >= 36 & fvfm >= 0.4 & f <= 250)) +
  facet_wrap(~ geno) +
  theme(legend.position = "none")
```
