---
title: "compare_fittogether"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(readxl)
library(janitor)
library(parzer)
library(broom)

library(lsmeans)
library(mcr)
library(ggpubr)
library(drc)
library(tidyverse)
```

```{r}
# Import data
clean_data_files <- list.files(path = "data/processed", 
                               pattern = "*_clean.csv", 
                               full.names = TRUE)
clean_data_files[c(1,3,5,6,7,9,10)]
clean_data <- clean_data_files[c(1,3,5,6,7,9,10)] %>% map_dfr(read_csv)

# Import genotype metadata
gmd <- read_csv("data/genotype_metadata.csv") %>%
  mutate(nursery = tolower(nursery),
         across(everything(), str_squish),
         across(ends_with("lat"), ~signif(parse_lat(.), 6)),             # parse latitude
         across(ends_with("lon"), ~signif(parse_lon(.), 6))) %>%        # parse longitude
  mutate(ugeno = gsub(" ", "", ugeno))

# Combine ed50 values with genotype metadata
df <- left_join(clean_data, gmd) %>%
  # Replace '(A)', etc. from geno names
  mutate(geno = str_replace(geno, "\\(.*\\)", "")) %>%
  mutate(geno = case_when(date == "2020-10" ~ ugeno,
                          date == "2020-06" & nursery == "mote" ~ paste0("ML", geno), 
                          date == "2020-06" & nursery == "fwc" ~ paste0("FM", geno),
                          TRUE ~ geno)) %>%
  # Order nurseries from south to north
  mutate(nursery = factor(nursery, levels = c("mote", "fwc", "rrt", "crf", "um", "nsu")))

# Filter to just corals run twice
df <- df %>%
  drop_na(date) %>%
  group_by(nursery, geno) %>%
  filter(n_distinct(date) == 2) %>%
  ungroup() %>%
  select(nursery, geno, date, max_temp, fvfm)
  
# Fit models
ll3 <- function(data) {
  drm(fvfm ~ max_temp, data = data, 
      fct = LL.3(names = c("hill", "max", "ED50")),
      upperl = c(120, 0.72, 40),
      lowerl = c(10, 0.55, 30))}

# Fit model to each coral, get parameters, fitted values, and residuals
mods <- df %>%
  nest(data = c(max_temp, fvfm)) %>%
  # Fit the model to each coral
  mutate(ll3 = map(data, ll3)) %>%
  # Get model parameters and fitted values/residuals
  mutate(pars = map(ll3, tidy),
         pred = map2(ll3, data, ~augment(.x, drop_na(.y, fvfm))))

# Extract ed50 parameter values from model fits
ed50 <- mods %>% 
  select(nursery, geno, date, pars) %>%
  unnest(pars) %>%
  filter(term == "ED50")
```

```{r}
# Combine May and Oct data, and select only genos incuded in both
ed50f <- ed50 %>% 
  mutate(date = recode(date, "2020-10" = "oct", "2020-06" = "jun")) %>%
  select(nursery, geno, date, ed50 = estimate, std.error) %>%
  pivot_wider(names_from = date, values_from = c(ed50, std.error)) %>%
  filter(geno != "FM19")


# Fit linear and Passing-Bablok regressions
library(mcr)
PBreg <- mcreg(ed50f$ed50_jun, ed50f$ed50_oct, method.reg = "PaBa",  method.ci = "bootstrap", nsamples = 9999)
bounds <- with(ed50f, range(c(ed50_jun - std.error_jun, ed50_jun + std.error_jun), na.rm = TRUE))
newdata <- tibble(ed50_may = seq(bounds[1], bounds[2], 0.01))
PBfit <- calcResponse(PBreg, x.levels = newdata$ed50_may, alpha = 0.05) %>%
  as_tibble()

# Plot figure
library(ggpubr)
fig <- ggplot(ed50f, aes(y = ed50_oct, x = ed50_jun)) +
  geom_errorbar(aes(xmin = ed50_jun - std.error_jun, xmax = ed50_jun + std.error_jun), lwd = 0.25) +
  geom_errorbar(aes(ymin = ed50_oct - std.error_oct, ymax = ed50_oct + std.error_oct), lwd = 0.25) +
  geom_point() +
  geom_label(aes(label = geno)) +
  labs(x = "ED50 (°C) measured in May", y = "ED50 (°C) measured in Oct.")

fig +
  #geom_line(data = PBfit, aes(x = X, y = Y), color = "blue") +
  #geom_ribbon(data = PBfit, aes(x = X, ymin = Y.LCI, ymax = Y.UCI), 
  #            inherit.aes = FALSE, alpha = 0.2, fill = "blue") +
  coord_cartesian(xlim = c(34.83,35.78), ylim=c(35,36.6)) +
  annotate(geom = "text", x = 34.82, y = 36.6, label = "Pearson's correlation:", adj = 0) +
  stat_cor(method = "pearson", label.y = 36.5, label.x = 34.85) +
  annotate(geom = "text", x = 34.82, y = 36.4, label = "Spearman's rank correlation:", adj = 0) +
  stat_cor(method = "spearman", label.y = 36.3, label.x = 34.85) +
  geom_abline(intercept = 0, slope = 1, lty = 2, color = "maroon") +
  geom_smooth(method = "lm") +
  geom_vline(aes(xintercept = median(ed50_jun))) +
  geom_hline(aes(yintercept = median(ed50_oct)))
```

```{r}
res <- ed50f %>%
  mutate(tophalfjun = ed50_jun > median(ed50_jun),
         tophalfoct = ed50_oct > median(ed50_oct),
         same = tophalfjun == tophalfoct)
table(res$same)
```

```{r}
# How often is may ranking predictive of june ranking for any random 2 genos?

compare2 <- function(df) {
  comp <- slice_sample(df, n = 2)
  comp1 <- comp$ed50_jun[1] > comp$ed50_jun[2]
  comp2 <- comp$ed50_oct[1] > comp$ed50_oct[2]
  return(comp1 == comp2)
}

compare2(ed50f)

res <- rerun(10000, compare2(ed50f))
table(unlist(res))

# If you pick two random genotypes and CBASS them each twice, 78% of the time you'll get the same ranking.
# This is identical to the Spearman rank correlation coefficient!
```





